data:
    class_path: datasets.LightningDataModule
    init_args:
        dataset_cfg:
            train:
                class_path: datasets.expi.ExPIDataset
                init_args:
                    data_root: data/ExPI
                    data_version: old_norm
                    # data_version: all_frame_origin
                    # data_version: all_frame_origin_spherical
                    # data_version: all_frame_origin_person_dfs
                    # data_version: all_frame_origin_person_bfs
                    # data_version: all_frame_origin_person_cascade_dfs
                    # data_version: all_frame_origin_person_cascade_bfs
                    # data_version: first_frame_origin
                    # data_version: first_frame_origin_spherical
                    # data_version: first_frame_origin_person_dfs
                    # data_version: first_frame_origin_person_bfs
                    # data_version: first_frame_origin_person_cascade_dfs
                    # data_version: first_frame_origin_person_cascade_bfs
                    input_n: 50
                    output_n: 10
                    protocol: common
            val:
                init_args:
                    output_n: 30
            test:
                init_args:
                    output_n: 30
            predict:
                init_args:
                    output_n: 30
        dataloader_cfg:
            batch_size: 32
            drop_last: true
            num_workers: 0
            pin_memory: true
        split_format_to: split

trainer:
    callbacks:
        change_item:
            - - -1
              - init_args:
                    monitor: val/jme
                    filename: "epoch:{epoch}-val_jme:{val/jme:.4g}"
